[BEGIN]
  Version=1
[END]
[BEGIN]
  ObjTp=FSgntr
  Sgntr=UserSPlus
  RelVrs=1
  IntStrVrs=1
  SPlusVrs=4.04.01
  CrossCplrVrs=1.3
[END]
[BEGIN]
  ObjTp=Hd
  Cmn1=Parameters\\\\Zone_Number: use the 3 digit number for the zone you||1
  Cmn2=wish to get status for i.e. 001\\Enable_Zone_Name: enable or disable||1
  Cmn3=this if you want to spit the zone name on the aptly named Zone_Name$||1
  Cmn4=signal\\\\Inputs \\\\From_Device$: This should come directly from||1
  Cmn5=the RX$ of COM port connected to the NX587E. The module will handle||1
  Cmn6=whether \\or not incoming strings are zone feedback strings and||1
  Cmn7=process things accordingly.\\\\Outputs\\\\zone_isXXXXX: This will||1
  Cmn8=go high whenever the zone is in the named state.\\zone_Name$: this||1
  Cmn9=will return the 16 character zone name, if you enable it. make sure||1
  Cmn10=you also enable Zone Name feedback \\on the main processor module,||1
  Cmn11=or it will print the unprocessed zone feedback. aka fTtBaillb \\
[END]
[BEGIN]
  ObjTp=Symbol
  Exclusions=1,19,20,21,88,89,167,168,179,213,214,215,216,217,225,226,248,249,266,267,310,362,378,380,405,407,408,409,478,522,537,554,586,590,611,624,718,756,767,830,841,842,854,883,955,1032,1062,1079,1128,1129,1134,1140,1157,1158,1195,1199,1220,1221,1222,1223,1299,1348,1349,1439,1472,1473,1499,1746,1803,1975,2229,2354,2514,2523,2532,2706,2707,3235,3236,3427,3454,3567,3568,3601,3602,3708,3902,3903,3912,3918,3925,3926,4206,4207,
  Exclusions_CDS=5
  Inclusions_CDS=6
  Name=NX-587E Zone Status Module
  SmplCName=_RB_Interlogix_Zone_Status_Decoder.usp
  Code=1
  SysRev5=4.006
  SMWRev=3.00.00
  OutputCue1=[~UNUSED~]
  OutputSigType1=Digital
  OutputCue2=[~UNUSED~]
  OutputSigType2=Digital
  OutputCue3=zone_isFaulted
  OutputSigType3=Digital
  OutputCue4=zone_isTamper
  OutputSigType4=Digital
  OutputCue5=zone_isTrouble
  OutputSigType5=Digital
  OutputCue6=zone_isBypass
  OutputSigType6=Digital
  OutputCue7=zone_isAlarmMemory
  OutputSigType7=Digital
  OutputCue8=zone_isInhibit
  OutputSigType8=Digital
  OutputCue9=zone_isLowBattery
  OutputSigType9=Digital
  OutputCue10=zone_isLost
  OutputSigType10=Digital
  OutputCue11=zone_isBypassMemory
  OutputSigType11=Digital
  InputList2Cue1=[~UNUSED~]
  InputList2SigType1=Serial
  InputList2Cue2=[~UNUSED~]
  InputList2SigType2=Serial
  InputList2Cue3=From_Device$
  InputList2SigType3=Serial
  OutputList2Cue1=[~UNUSED~]
  OutputList2SigType1=Serial
  OutputList2Cue2=Zone_Name$
  OutputList2SigType2=Serial
  ParamCue1=[Reference Name]
  ParamCue2=Zone_Number
  ParamSigType2=String
  ParamCue3=Enable_Zone_Name,1d,0d
  ParamSigType3=List
  MinVariableInputs=0
  MaxVariableInputs=0
  MinVariableInputsList2=3
  MaxVariableInputsList2=3
  MinVariableOutputs=11
  MaxVariableOutputs=11
  MinVariableOutputsList2=2
  MaxVariableOutputsList2=2
  MinVariableParams=2
  MaxVariableParams=2
  Expand=expand_separately
  Expand2=expand_separately
  ProgramTree=Logic
  SymbolTree=21
  Hint=takes serial responses from the NX-587E and parses out information. Dont forget to choose whether or not to use the zone name, and to enable zone names in the main processor module.
  PdfHelp=
  HelpID= 
  Render=4
  Smpl-C=16
  CompilerCode=-48
  CompilerParamCode=27
  CompilerParamCode5=14
  NumFixedParams=1
  Pp1=1
  Pp2=2
  Pp3=3
  MPp=3
  NVStorage=10
  ParamSigType1=String
  SmplCInputCue1=o#
  SmplCOutputCue1=i#
  SmplCInputList2Cue1=an#
  SmplCOutputList2Cue1=ai#
  SPlus2CompiledName=S2__RB_Interlogix_Zone_Status_Decoder
  SymJam=NonExclusive
  FileName=_RB_Interlogix_Zone_Status_Decoder.ush
  SIMPLPlusModuleEncoding=0
  clz1=Crestron.RemoteServiceSimpl
  clz2=IFTTT
[END]
[BEGIN]
  ObjTp=Dp
  H=1
  Tp=1
  NoS=False
[END]
[BEGIN]
  ObjTp=Dp
  H=2
  Tp=1
  HD=False
  NoS=False
  VVS=0
[END]
[BEGIN]
  ObjTp=Dp
  H=3
  Tp=1
  SD=Parse Zone Name?
  HD=True
  DV=1d
  Sgn=0
  Lng=False
  NF=1
  NoS=True
  DNF=1
  VVS=2
  VN=2
  Val1=1d
  Lbl1=Yes
  Val2=0d
  Lbl2=No
[END]
