[BEGIN]
  Version=1
[END]
[BEGIN]
  ObjTp=FSgntr
  Sgntr=UserSPlus
  RelVrs=1
  IntStrVrs=1
  SPlusVrs=4.04.01
  CrossCplrVrs=1.3
[END]
[BEGIN]
  ObjTp=Hd
  Cmn1=INPUTS:\\ValueToCompare: A value we want to compare all our Input_[X]||1
  Cmn2=values against. Depending on the use case this value may not change.
  Cmn3=||1\\Input_[X]: a value we wish to compare against ValueToCompare||1
  Cmn4=to see if it matches. This value will change based on a certain||1
  Cmn5=state, such as DM Output Fb Corrected\\\\OUTPUTS:\\Match[X]:A digital||1
  Cmn6=signal that will go high if ValueToCompare = Input[X]\\TotalCount:
  Cmn7=||1A count of the total amount of matching values. Havent experienced||1
  Cmn8=a use case for this... but its there just in case. \\\\Use Cases:
  Cmn9=||1\\- show a user which displays are currently displaying the source||1
  Cmn10=they have selected.\\- check if a display has an active source and||1
  Cmn11=do something if it does.\\
[END]
[BEGIN]
  ObjTp=Symbol
  Exclusions=1,19,20,21,88,89,167,168,179,213,214,215,216,217,225,226,248,249,266,267,310,718,756,854,
  Exclusions_CDS=5
  Inclusions_CDS=6
  Name=Multiple Analog Compare (Basic Sieve)
  SmplCName=_RB_AnalogCompare_v1.usp
  Code=1
  SysRev5=4.006
  SMWRev=3.00.00
  OutputCue1=Match[#]
  OutputSigType1=Digital
  InputList2Cue1=ValueToCompare
  InputList2SigType1=Analog
  InputList2Cue2=Input_[#]
  InputList2SigType2=Analog
  OutputList2Cue1=TotalCount
  OutputList2SigType1=Analog
  ParamCue1=[Reference Name]
  MinVariableInputs=0
  MaxVariableInputs=0
  MinVariableInputsList2=2
  MaxVariableInputsList2=256
  MinVariableOutputs=1
  MaxVariableOutputs=255
  MinVariableOutputsList2=1
  MaxVariableOutputsList2=1
  MinVariableParams=0
  MaxVariableParams=0
  Expand=expand_separately
  Expand2=expand_separately
  OffsetOutputs=1
  ProgramTree=Logic
  SymbolTree=46
  UserSymTreeName=RBLAJDA
  Hint=compares multiple analog values against one test value
  PdfHelp=
  HelpID= 
  Render=4
  Smpl-C=16
  CompilerCode=-48
  CompilerParamCode=27
  CompilerParamCode5=14
  NumFixedParams=1
  Pp1=1
  MPp=1
  NVStorage=10
  ParamSigType1=String
  SmplCInputCue1=o#
  SmplCOutputCue1=i#
  SmplCInputList2Cue1=an#
  SmplCOutputList2Cue1=ai#
  SPlus2CompiledName=S2__RB_AnalogCompare_v1
  SymJam=NonExclusive
  FileName=_RB_AnalogCompare_v1.ush
  SIMPLPlusModuleEncoding=0
  clz1=QsysControlV4_2
  clz2=UserNotifications
[END]
[BEGIN]
  ObjTp=Dp
  H=1
  Tp=1
  NoS=False
[END]
