[BEGIN]
  Version=1
[END]
[BEGIN]
  ObjTp=FSgntr
  Sgntr=UserSPlus
  RelVrs=1
  IntStrVrs=1
  SPlusVrs=4.02.20
  CrossCplrVrs=1.3
[END]
[BEGIN]
  ObjTp=Hd
  Cmn1=This module serializes the current time in either 12 or 24 hour||1
  Cmn2=format with or with out the AM/PM designation. The module\\updates||1
  Cmn3=the output, 'time$' every minute, but can be forced to do so more||1
  Cmn4=often.\\\\DIGITAL_INPUT\\Manual_Update - Forces an update of 'Time$'\\
  Cmn5=\\STRING_OUTPUT\\Time$ - A serial string of the current time in||1
  Cmn6=the format specified by the parameters\\\\INTEGER_PARAMETER\\Time_Format||1
  Cmn7=- Renders 'Time$' in either 24 hour or 12 hour format\\AM_PM_Append||1
  Cmn8=- When paremeter 'Time-Format' is set to 12 hour, use this parameter||1
  Cmn9=to either add or not add the AM/PM designation\\to 'time$'
[END]
[BEGIN]
  ObjTp=Symbol
  Exclusions=1,19,20,21,88,89,167,168,179,213,214,215,216,217,225,226,248,249,266,267,310,718,756,854,
  Exclusions_CDS=6
  Inclusions_CDS=5
  Name=PDT Serial Time v1.1
  SmplCName=PDT Serial Time v1.1.usp
  Code=1
  SysRev5=4.000
  SMWRev=2.02.05
  InputCue1=[~UNUSED~]
  InputSigType1=Digital
  InputCue2=[~UNUSED~]
  InputSigType2=Digital
  InputCue3=Manual_Update
  InputSigType3=Digital
  OutputList2Cue1=[~UNUSED~]
  OutputList2SigType1=Serial
  OutputList2Cue2=[~UNUSED~]
  OutputList2SigType2=Serial
  OutputList2Cue3=Time$
  OutputList2SigType3=Serial
  ParamCue1=[Reference Name]
  ParamCue2=Time_Format,1d,2d
  ParamSigType2=List
  ParamCue3=AM_PM_Append,0d,1d
  ParamSigType3=List
  MinVariableInputs=3
  MaxVariableInputs=3
  MinVariableInputsList2=0
  MaxVariableInputsList2=0
  MinVariableOutputs=0
  MaxVariableOutputs=0
  MinVariableOutputsList2=3
  MaxVariableOutputsList2=3
  MinVariableParams=2
  MaxVariableParams=2
  Expand=expand_separately
  Expand2=expand_separately
  ProgramTree=Logic
  SymbolTree=16
  Hint=
  PdfHelp=
  HelpID= 
  Render=4
  Smpl-C=16
  CompilerCode=-48
  CompilerParamCode=27
  CompilerParamCode5=14
  NumFixedParams=1
  Pp1=1
  Pp2=2
  Pp3=3
  MPp=3
  NVStorage=10
  ParamSigType1=String
  SmplCInputCue1=o#
  SmplCOutputCue1=i#
  SmplCInputList2Cue1=an#
  SmplCOutputList2Cue1=ai#
  SPlus2CompiledName=S2_PDT_Serial_Time_v1_1
  SymJam=NonExclusive
  FileName=PDT Serial Time v1.1.ush
[END]
[BEGIN]
  ObjTp=Dp
  H=1
  Tp=1
  NoS=False
[END]
[BEGIN]
  ObjTp=Dp
  H=2
  Tp=1
  SD=Time output format.
  HD=True
  DV=1d
  Sgn=0
  Lng=False
  NF=1
  NoS=True
  DNF=1
  VVS=2
  VN=2
  Val1=1d
  Lbl1=24 hour
  Val2=2d
  Lbl2=12 hour
[END]
[BEGIN]
  ObjTp=Dp
  H=3
  Tp=1
  SD=Append the AM or PM designation
  HD=True
  DV=0d
  Sgn=0
  Lng=False
  NF=1
  NoS=True
  DNF=1
  VVS=2
  VN=2
  Val1=0d
  Lbl1=No
  Val2=1d
  Lbl2=Yes
[END]
