[BEGIN]
  Version=1
[END]
[BEGIN]
  ObjTp=FSgntr
  Sgntr=UserSPlus
  RelVrs=1
  IntStrVrs=1
  SPlusVrs=4.06.00
  CrossCplrVrs=1.3
[END]
[BEGIN]
  ObjTp=Hd
  Cmn1=	"dd/MM/yyyy"	25-04-2025	/ the system date separator\\	"yyyy MMMM"	
  Cmn2=2025 April	MMMM name of the month\\	"MMM d"	Apr 25	 MMM abbreviated||1
  Cmn3=name of the month\\	"ddd, dd MMM yy"	Thu, 25 Apr 24	yy the year,||1
  Cmn4=from 00 to 99.\\	ddd abbreviated name of the day\\	"dddd, dd MMMM||1
  Cmn5=yyyy"	Friday, 25 April 2025	dddd name of the day\\	"ddd, dd MMM||1
  Cmn6=yyyy h:mm"	Thu, 25 Apr 2025 5:07	date and time together\\	"yyyy-
  Cmn7=MM-dd HH:mm:ss"	2025-04-25 17:07:17	Format that can be sorted :||1
  Cmn8=the system time separator HH hour from 00 to 23\\	"hh:mm:ss tt"	
  Cmn9=05:07:06 PM	tt the AM/PM designator.\\	hh hour from 00 to 11\\	"h:
  Cmn10=m:s t"	5:7:6 P	t the A/M designator.\\	No leading 0 with h m s\\
  Cmn11=	"H:mm:ss"	17:07:06	H hour from 0 to 23\\	"HH:mm:ss.ff"	17:07:06.
  Cmn12=73	f for a fraction of a second\\	"HH:mm:ss.fffffff"	17:07:06.7301481	
  Cmn13=use as many f as needed\\	"HH:mm:ss UTC"	17:07:06 UTC	UTC chars||1
  Cmn14=are not interpreted\\	"hh:mm:ss K"	05:07:06 +04:00	 K time zone||1
  Cmn15=information.\\	"hh:mm:ss z"	05:07:06 +4	 z time zone information||1
  Cmn16=from UTC.\\	"hh:mm:ss zz"	05:07:06 +04	 zz time zone information||1
  Cmn17=from UTC with leading zero\\	"HH:\\mm"	17:m7	\ is the escape character||1
  Cmn18=need \\ in a C# literal string @"HH:\mm"	17:m7	\ escape character,||1
  Cmn19=don’t need \\ in a C# verbatim literal string @"…"\\	"HH:'mm':ss"	
  Cmn20=17:mm:06	chars in '…' are escaped\\	"HH:\"mm\":ss"	17:mm:06	chars||1
  Cmn21=in "…" are escaped
[END]
[BEGIN]
  ObjTp=Symbol
  Exclusions=1,19,20,21,88,89,167,168,179,213,214,215,216,217,225,226,248,249,266,267,310,362,378,380,405,407,408,409,478,522,537,554,586,590,611,624,718,756,767,830,841,842,854,883,955,1032,1062,1079,1128,1129,1134,1140,1157,1158,1195,1199,1220,1221,1222,1223,1299,1348,1349,1439,1472,1473,1499,1746,1803,1975,2229,2354,2514,2523,2532,2706,2707,3235,3236,3427,3454,3567,3568,3601,3602,3708,3902,3903,3912,3918,3925,3926,4206,4207,
  Exclusions_CDS=5
  Inclusions_CDS=6,7
  Name=Formatted Date Time String
  SmplCName=_RB_FormattedDateTime_v1.usp
  Code=1
  SysRev5=4.000
  SMWRev=2.02.05
  OutputCue1=[~UNUSED~]
  OutputSigType1=Digital
  OutputCue2=Error_Fb
  OutputSigType2=Digital
  OutputList2Cue1=Formatted_DateTime
  OutputList2SigType1=Serial
  ParamCue1=[Reference Name]
  ParamCue2=DateTimeFormat
  ParamSigType2=String
  MinVariableInputs=0
  MaxVariableInputs=0
  MinVariableInputsList2=0
  MaxVariableInputsList2=0
  MinVariableOutputs=2
  MaxVariableOutputs=2
  MinVariableOutputsList2=1
  MaxVariableOutputsList2=1
  MinVariableParams=1
  MaxVariableParams=1
  Expand=expand_separately
  Expand2=expand_separately
  ProgramTree=Logic
  SymbolTree=46
  UserSymTreeName=RBLAJDA-C#
  Hint=outputs a formatted date time string to a touchpanel, allowing for custom font, color & formatting.
  PdfHelp=
  HelpID= 
  Render=4
  Smpl-C=16
  CompilerCode=-48
  CompilerParamCode=27
  CompilerParamCode5=14
  NumFixedParams=1
  Pp1=1
  Pp2=2
  MPp=2
  NVStorage=10
  ParamSigType1=String
  SmplCInputCue1=o#
  SmplCOutputCue1=i#
  SmplCInputList2Cue1=an#
  SmplCOutputList2Cue1=ai#
  SPlus2CompiledName=S2__RB_FormattedDateTime_v1
  SymJam=NonExclusive
  FileName=_RB_FormattedDateTime_v1.ush
  SIMPLPlusModuleEncoding=0
  clz1=FormattedTimeDateString
[END]
[BEGIN]
  ObjTp=Dp
  H=1
  Tp=1
  NoS=False
[END]
[BEGIN]
  ObjTp=Dp
  H=2
  Tp=1
  HD=False
  NoS=False
  VVS=0
[END]
