[BEGIN]
  Version=1
[END]
[BEGIN]
  ObjTp=FSgntr
  Sgntr=UserSPlus
  RelVrs=1
  IntStrVrs=1
  SPlusVrs=4.06.00
  CrossCplrVrs=1.3
[END]
[BEGIN]
  ObjTp=Hd
  Cmn1=INPUTS\\\\Filter_Number: a number that will be compared against||1
  Cmn2=the Filter_List parameter for each input\\\\Item_IsDefined: a digital||1
  Cmn3=signal representing whether the item has been "defined" \\\\OUTPUTS\\
  Cmn4=Item_IsVisible: when the Filter_Number value exists in the Filter_List||1
  Cmn5=for this item, AND Item_IsDefined is HIGH for the associated input,||1
  Cmn6=it will be high.\\\\PARAMETERS\\\\Filter_List: a list of Filter_Number||1
  Cmn7=values in which an Item_IsDefined input should be allowed to propogate||1
  Cmn8=to its associated Item_IsVisible output.
[END]
[BEGIN]
  ObjTp=Symbol
  Exclusions=1,19,20,21,88,89,167,168,179,213,214,215,216,217,225,226,248,249,266,267,310,718,756,854,
  Exclusions_CDS=
  Inclusions_CDS=5,6,7
  Name=Item Visibility Filter Dynamic v1
  SmplCName=_RB_DisplayVisibilityDynamic.usp
  Code=1
  SysRev5=4.006
  SMWRev=3.00.00
  InputCue1=Enable
  InputSigType1=Digital
  InputCue2=[~UNUSED~]
  InputSigType2=Digital
  InputCue3=Item_IsDefined[#]
  InputSigType3=Digital
  OutputCue1=[~UNUSED~]
  OutputSigType1=Digital
  OutputCue2=[~UNUSED~]
  OutputSigType2=Digital
  OutputCue3=Item_IsVisible[#]
  OutputSigType3=Digital
  InputList2Cue1=Filter_Number
  InputList2SigType1=Analog
  InputList2Cue2=[~UNUSED~]
  InputList2SigType2=Serial
  InputList2Cue3=[~UNUSED~]
  InputList2SigType3=Serial
  InputList2Cue4=Filter_List[#]
  InputList2SigType4=Serial
  ParamCue1=[Reference Name]
  MinVariableInputs=3
  MaxVariableInputs=257
  MinVariableInputsList2=4
  MaxVariableInputsList2=258
  MinVariableOutputs=3
  MaxVariableOutputs=257
  MinVariableOutputsList2=0
  MaxVariableOutputsList2=0
  MinVariableParams=0
  MaxVariableParams=0
  Expand=expand_inputs_with_outputs
  Expand2=expand_inputs_with_outputs
  ProgramTree=Logic
  SymbolTree=46
  UserSymTreeName=RBLAJDA
  Hint=Shows Items Based On Analog Join
  PdfHelp=
  HelpID= 
  Render=4
  Smpl-C=16
  CompilerCode=-48
  CompilerParamCode=27
  CompilerParamCode5=14
  NumFixedParams=1
  Pp1=1
  MPp=1
  NVStorage=10
  ParamSigType1=String
  SmplCInputCue1=o#
  SmplCOutputCue1=i#
  SmplCInputList2Cue1=an#
  SmplCOutputList2Cue1=ai#
  SPlus2CompiledName=S2__RB_DisplayVisibilityDynamic
  SymJam=NonExclusive
  FileName=_RB_DisplayVisibilityDynamic.ush
  SIMPLPlusModuleEncoding=0
[END]
[BEGIN]
  ObjTp=Dp
  H=1
  Tp=1
  NoS=False
[END]
