[BEGIN]
  Version=1
[END]
[BEGIN]
  ObjTp=FSgntr
  Sgntr=UserSPlus
  RelVrs=1
  IntStrVrs=1
  SPlusVrs=4.05.01
  CrossCplrVrs=1.3
[END]
[BEGIN]
  ObjTp=Hd
  Cmn1=AandH Zone Source Selector-AHM64 r0.0\\\\Controls setting Input||1
  Cmn2=Channels on Zone Source Selectors.\\\\Parameters:\\ ZoneChnl: Select||1
  Cmn3=valid range from control type in decimal format.\\ \\Inputs:\\ Digital-
  Cmn4=\\ 	Take: Send selected source. Can be pulsed or Latch to 1 to always||1
  Cmn5=send. \\ Analog-\\  Source: Decimal Value of Source to activate.
  Cmn6=||1Valid range is 1d ~ 14d.\\  \\ Serial-\\  FmMixer: Connect to the||1
  Cmn7=TCP/IP symbol receive line. (For Future Use)\\\\Outputs:\\ Analog-
  Cmn8=\\  SourceFb: Decimal Value of Active Source. Valid range is 1d||1
  Cmn9=~ 14d.\\      Note that feedback is tracked internal to this module||1
  Cmn10=and is not available from the\\      DSP at this time.\\  \\ Serial-
  Cmn11=\\  ToMixer: Connect to the TCP/IP symbol Transmit line.\\\\Notes:
  Cmn12=\\ Reference the AHM64 protocol for valid Control Channels for the\\
  Cmn13=||2selected control type.\\\\ For more information Reference: AHM-
  Cmn14=TCP-Protocol-V1.pdf\\\\ Tested with AHM64 Firmware V1.02 - Rev59154\\
  Cmn15=\\ Release: 2020-Nov-19 Release r0.0\\
[END]
[BEGIN]
  ObjTp=Symbol
  Exclusions=1,19,20,21,88,89,167,168,179,213,214,215,216,217,225,226,248,249,266,267,310,362,378,380,405,407,408,409,478,522,537,554,586,590,611,624,718,756,767,830,841,842,854,883,955,1032,1062,1079,1128,1129,1134,1140,1157,1158,1195,1199,1220,1221,1222,1223,1299,1348,1349,1439,1472,1473,1499,1746,1803,1975,2229,2354,2514,2523,2532,2706,2707,3235,3236,3427,3454,3567,3568,3601,3602,3708,3902,3903,3912,3918,3925,3926,4206,4207,
  Exclusions_CDS=5
  Inclusions_CDS=6,7
  Name=AandH Zone Source Selector-AHM64
  SmplCName=AandH Zone Source Selector-AHM64 r0.0.usp
  Code=1
  SysRev5=4.006
  SMWRev=3.00.00
  InputCue1=[~UNUSED~]
  InputSigType1=Digital
  InputCue2=Take
  InputSigType2=Digital
  InputList2Cue1=Source
  InputList2SigType1=Analog
  InputList2Cue2=FmMixer
  InputList2SigType2=Serial
  OutputList2Cue1=[~UNUSED~]
  OutputList2SigType1=Analog
  OutputList2Cue2=[~UNUSED~]
  OutputList2SigType2=Analog
  OutputList2Cue3=SourceFb
  OutputList2SigType3=Analog
  OutputList2Cue4=ToMixer
  OutputList2SigType4=Serial
  ParamCue1=[Reference Name]
  ParamCue2=ZoneChnl
  ParamSigType2=Constant
  MinVariableInputs=2
  MaxVariableInputs=2
  MinVariableInputsList2=2
  MaxVariableInputsList2=2
  MinVariableOutputs=0
  MaxVariableOutputs=0
  MinVariableOutputsList2=4
  MaxVariableOutputsList2=4
  MinVariableParams=1
  MaxVariableParams=1
  Expand=expand_separately
  Expand2=expand_separately
  ProgramTree=Logic
  SymbolTree=34
  Hint=
  PdfHelp=
  HelpID= 
  Render=4
  Smpl-C=16
  CompilerCode=-48
  CompilerParamCode=27
  CompilerParamCode5=14
  NumFixedParams=1
  Pp1=1
  Pp2=2
  MPp=2
  NVStorage=10
  ParamSigType1=String
  SmplCInputCue1=o#
  SmplCOutputCue1=i#
  SmplCInputList2Cue1=an#
  SmplCOutputList2Cue1=ai#
  SPlus2CompiledName=S2_AandH_Zone_Source_Selector_AHM64_r0_0
  SymJam=NonExclusive
  FileName=AandH Zone Source Selector-AHM64 r0.0.ush
  SIMPLPlusModuleEncoding=0
[END]
[BEGIN]
  ObjTp=Dp
  H=1
  Tp=1
  NoS=False
[END]
[BEGIN]
  ObjTp=Dp
  H=2
  Tp=1
  HD=True
  DV=1d
  Sgn=0
  Lng=False
  NF=1
  NoS=True
  DNF=1
  VVS=1
  LR=1d
  HR=64d
[END]
