[BEGIN]
  Version=1
[END]
[BEGIN]
  ObjTp=FSgntr
  Sgntr=UserSPlus
  RelVrs=1
  IntStrVrs=1
  SPlusVrs=4.06.00
  CrossCplrVrs=1.3
[END]
[BEGIN]
  ObjTp=Hd
  Cmn1=INPUTS:\\	String_To_Search: the string containing content you want||1
  Cmn2=to find\\\\PARAMETERS:\\	StringToFind: a string to find that ends||1
  Cmn3=where you wish your substring to begin\\	Delimiter: a string or||1
  Cmn4=character that denotes the end of the substring [not included in||1
  Cmn5=the extracted substring output]\\\\example: \\\\String_To_Search||1
  Cmn6=== {"error": false,"config": {"motion": {"detected": true,"lastDetection":
  Cmn7=||1"0:00:00:09","activeDelay": 3,"noDelay": 3}}}\\StringToFind = "detected":
  Cmn8=\\Delimiter = ,\\\\Substring = \x20true\\\\\\OUTPUTS:\\	Substring:
  Cmn9=||1the resulting substring you wish to extract\\
[END]
[BEGIN]
  ObjTp=Symbol
  Exclusions=1,19,20,21,88,89,167,168,179,213,214,215,216,217,225,226,248,249,266,267,310,718,756,854,
  Exclusions_CDS=
  Inclusions_CDS=5,6,7
  Name=Serial Substring
  SmplCName=_RB_SerialSubstring.usp
  Code=1
  SysRev5=4.000
  SMWRev=2.02.05
  InputList2Cue1=[~UNUSED~]
  InputList2SigType1=Serial
  InputList2Cue2=[~UNUSED~]
  InputList2SigType2=Serial
  InputList2Cue3=String_To_Search
  InputList2SigType3=Serial
  OutputList2Cue1=[~UNUSED~]
  OutputList2SigType1=Serial
  OutputList2Cue2=[~UNUSED~]
  OutputList2SigType2=Serial
  OutputList2Cue3=Substring
  OutputList2SigType3=Serial
  ParamCue1=[Reference Name]
  ParamCue2=StringToFind
  ParamSigType2=String
  ParamCue3=Delimiter
  ParamSigType3=String
  MinVariableInputs=0
  MaxVariableInputs=0
  MinVariableInputsList2=3
  MaxVariableInputsList2=3
  MinVariableOutputs=0
  MaxVariableOutputs=0
  MinVariableOutputsList2=3
  MaxVariableOutputsList2=3
  MinVariableParams=2
  MaxVariableParams=2
  Expand=expand_separately
  Expand2=expand_separately
  ProgramTree=Logic
  SymbolTree=46
  UserSymTreeName=RBLAJDA
  Hint=finds a substring
  PdfHelp=
  HelpID= 
  Render=4
  Smpl-C=16
  CompilerCode=-48
  CompilerParamCode=27
  CompilerParamCode5=14
  NumFixedParams=1
  Pp1=1
  Pp2=2
  Pp3=3
  MPp=3
  NVStorage=10
  ParamSigType1=String
  SmplCInputCue1=o#
  SmplCOutputCue1=i#
  SmplCInputList2Cue1=an#
  SmplCOutputList2Cue1=ai#
  SPlus2CompiledName=S2__RB_SerialSubstring
  SymJam=NonExclusive
  FileName=_RB_SerialSubstring.ush
  SIMPLPlusModuleEncoding=0
[END]
[BEGIN]
  ObjTp=Dp
  H=1
  Tp=1
  NoS=False
[END]
[BEGIN]
  ObjTp=Dp
  H=2
  Tp=1
  HD=False
  NoS=False
  VVS=0
[END]
[BEGIN]
  ObjTp=Dp
  H=3
  Tp=1
  HD=False
  NoS=False
  VVS=0
[END]
